import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import folium
import qrcode
from io import BytesIO
from streamlit_folium import st_folium

# =========================================================
# PAGE CONFIG
# =========================================================

st.set_page_config(
    page_title="EcoSim AI | Karachi Climate Lab",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =========================================================
# COLORS / UI
# Soft Green RGB = 232, 245, 238
# =========================================================

st.markdown("""
<style>

@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');

html, body, [class*="css"] {
    font-family: 'Inter', sans-serif;
}

.stApp {
    background-color: rgb(232,245,238);
}

.block-container {
    max-width: 1400px;
    padding-top: 2rem;
    padding-bottom: 3rem;
}

/* HERO */

.hero {
    background: linear-gradient(
        135deg,
        #ffffff 0%,
        #e8f5ee 55%,
        #d7f0e2 100%
    );

    padding: 38px;
    border-radius: 26px;
    border: 1px solid #cde5d7;
    margin-bottom: 25px;

    box-shadow: 0 10px 30px rgba(20,80,50,0.08);
}

.hero h1 {
    color: #075c38;
    font-size: 44px;
    font-weight: 800;
    margin: 0;
}

.hero p {
    color: #53665c;
    font-size: 16px;
}

.badge {
    display: inline-block;
    padding: 6px 14px;
    border-radius: 50px;
    background: #d5efdf;
    color: #075c38;
    font-size: 12px;
    font-weight: 700;
    margin-bottom: 12px;
}

/* SECTION */

.section-title {
    color: #075c38;
    font-size: 25px;
    font-weight: 800;
    margin-top: 30px;
    margin-bottom: 15px;
}

/* CARDS */

.card {
    background: white;
    border-radius: 18px;
    padding: 22px;

    border: 1px solid #dce9e1;

    box-shadow: 0 5px 18px rgba(20,60,40,0.06);
}

.metric-title {
    color: #65766d;
    font-size: 13px;
    font-weight: 600;
}

.metric-value {
    color: #075c38;
    font-size: 28px;
    font-weight: 800;
    margin-top: 5px;
}

.metric-delta {
    color: #11945b;
    font-size: 12px;
    font-weight: 700;
    margin-top: 4px;
}

/* INFO */

.info-box {
    background: white;
    border-left: 5px solid #15915c;
    padding: 15px 18px;
    border-radius: 12px;
    color: #365348;
    font-size: 13px;
    margin-bottom: 20px;
}

/* SIDEBAR */

section[data-testid="stSidebar"] {
    background-color: #075c38;
}

section[data-testid="stSidebar"] * {
    color: white !important;
}

/* BUTTON */

.stButton > button {
    border-radius: 12px;
    font-weight: 700;
    border: none;
}

/* FOOTER */

.footer {
    text-align: center;
    color: #718078;
    font-size: 12px;
    padding: 25px;
}

</style>
""", unsafe_allow_html=True)

# =========================================================
# BASELINE DATA
# =========================================================

BASE_TEMP = 41.75
BASE_GREEN = 0.155

KARACHI_AREA = 5841.13
BUILDINGS = 128285
PARKS = 1148
PARK_AREA = 9.04

WATER_BODIES = 279
WATER_AREA = 252.32

# =========================================================
# MODEL PARAMETERS
# =========================================================

SURVIVAL_RATE = 0.80

# Estimated canopy area generated by one surviving tree
CANOPY_PER_TREE = 0.00002


# =========================================================
# COOLING MODEL
# =========================================================

def estimate_cooling(canopy_increase):

    if canopy_increase <= 0:
        return 0

    elif canopy_increase <= 10:
        return 0.8 * (canopy_increase / 10)

    elif canopy_increase <= 20:
        return 0.8 + (
            0.3 *
            ((canopy_increase - 10) / 10)
        )

    elif canopy_increase <= 30:
        return 1.1 + (
            0.4 *
            ((canopy_increase - 20) / 10)
        )

    else:
        return 1.5


# =========================================================
# CO2 MODEL
# =========================================================

def calculate_co2_range(trees):

    low_rate = 10
    high_rate = 25

    low = trees * low_rate / 1000
    high = trees * high_rate / 1000

    return low, high


# =========================================================
# ECOSIM ENGINE
# =========================================================

def run_ecosim(trees_planted, intervention_area):

    surviving_trees = int(
        trees_planted * SURVIVAL_RATE
    )

    added_canopy = (
        surviving_trees *
        CANOPY_PER_TREE
    )

    # Prevent canopy from exceeding selected area
    added_canopy = min(
        added_canopy,
        intervention_area
    )

    canopy_increase = (
        added_canopy /
        intervention_area
    ) * 100

    cooling = estimate_cooling(
        canopy_increase
    )

    predicted_temperature = (
        BASE_TEMP - cooling
    )

    new_green_cover = (
        BASE_GREEN +
        canopy_increase
    )

    co2_low, co2_high = (
        calculate_co2_range(
            surviving_trees
        )
    )

    return {

        "trees_planted": trees_planted,

        "surviving_trees": surviving_trees,

        "intervention_area": intervention_area,

        "added_canopy": added_canopy,

        "canopy_increase": canopy_increase,

        "green_before": BASE_GREEN,

        "green_after": new_green_cover,

        "temperature_before": BASE_TEMP,

        "temperature_after": predicted_temperature,

        "cooling": cooling,

        "co2_low": co2_low,

        "co2_high": co2_high
    }


# =========================================================
# HERO
# =========================================================

st.markdown("""
<div class="hero">

<div class="badge">
SDG 11 • SDG 13
</div>

<h1>🌍 EcoSim AI</h1>

<p>
<b>Karachi Climate Simulation Lab</b>
</p>

<p>
Explore how nature-based urban interventions can
potentially influence green cover, temperature,
and CO₂ removal.
</p>

</div>
""", unsafe_allow_html=True)


# =========================================================
# SIDEBAR
# =========================================================

st.sidebar.markdown("## 🌱 Simulation Controls")

st.sidebar.write(
    "Create your own Karachi climate scenario."
)

trees = st.sidebar.slider(
    "🌳 Trees to Plant",
    min_value=10_000,
    max_value=2_000_000,
    value=500_000,
    step=10_000
)

area = st.sidebar.slider(
    "📍 Intervention Zone (km²)",
    min_value=10,
    max_value=500,
    value=100,
    step=10
)

st.sidebar.markdown("---")

st.sidebar.markdown("### Model Assumptions")

st.sidebar.write("🌳 Tree survival: 80%")
st.sidebar.write("🌿 Canopy: 0.00002 km²/tree")
st.sidebar.write("🌡 Cooling: scenario-based")
st.sidebar.write("🌍 CO₂: 10–25 kg/tree/year")


# =========================================================
# RUN MODEL
# =========================================================

result = run_ecosim(
    trees,
    area
)


# =========================================================
# DISCLAIMER
# =========================================================

st.markdown("""
<div class="info-box">

⚠️ <b>Scenario Estimate:</b>
EcoSim AI provides exploratory estimates based on
model assumptions. Results are not guaranteed future
measurements.

</div>
""", unsafe_allow_html=True)


# =========================================================
# OVERVIEW CARDS
# =========================================================

st.markdown(
    '<div class="section-title">📊 Simulation Overview</div>',
    unsafe_allow_html=True
)

col1, col2, col3, col4 = st.columns(4)


with col1:

    st.markdown(f"""
    <div class="card">

    <div class="metric-title">
    🌳 Surviving Trees
    </div>

    <div class="metric-value">
    {result["surviving_trees"]:,}
    </div>

    <div class="metric-delta">
    80% estimated survival
    </div>

    </div>
    """, unsafe_allow_html=True)


with col2:

    st.markdown(f"""
    <div class="card">

    <div class="metric-title">
    🌿 Green Cover
    </div>

    <div class="metric-value">
    {result["green_after"]:.3f}%
    </div>

    <div class="metric-delta">
    +{result["canopy_increase"]:.3f} percentage points
    </div>

    </div>
    """, unsafe_allow_html=True)


with col3:

    st.markdown(f"""
    <div class="card">

    <div class="metric-title">
    🌡️ Temperature
    </div>

    <div class="metric-value">
    {result["temperature_after"]:.2f}°C
    </div>

    <div class="metric-delta">
    ↓ {result["cooling"]:.2f}°C cooling
    </div>

    </div>
    """, unsafe_allow_html=True)


with col4:

    st.markdown(f"""
    <div class="card">

    <div class="metric-title">
    🌍 CO₂ Removal
    </div>

    <div class="metric-value">
    {result["co2_low"]:,.0f}–
    {result["co2_high"]:,.0f}
    </div>

    <div class="metric-delta">
    tons / year
    </div>

    </div>
    """, unsafe_allow_html=True)


# =========================================================
# INTERVENTION SUMMARY
# =========================================================

st.markdown(
    '<div class="section-title">🌱 Intervention Impact</div>',
    unsafe_allow_html=True
)

a, b = st.columns(2)


with a:

    st.markdown(
        '<div class="card">',
        unsafe_allow_html=True
    )

    st.markdown("### 🌿 Green Cover")

    st.write(
        f"""
        **Baseline:** {result["green_before"]:.3f}%

        **Scenario:** {result["green_after"]:.3f}%

        **Added canopy:** {result["added_canopy"]:.2f} km²
        """
    )

    st.markdown(
        '</div>',
        unsafe_allow_html=True
    )


with b:

    st.markdown(
        '<div class="card">',
        unsafe_allow_html=True
    )

    st.markdown("### 🌡️ Temperature")

    st.write(
        f"""
        **Baseline:** {result["temperature_before"]:.2f}°C

        **Scenario:** {result["temperature_after"]:.2f}°C

        **Estimated cooling:** {result["cooling"]:.2f}°C
        """
    )

    st.markdown(
        '</div>',
        unsafe_allow_html=True
    )


# =========================================================
# ANALYTICS
# =========================================================

st.markdown(
    '<div class="section-title">📈 Climate Impact Analytics</div>',
    unsafe_allow_html=True
)

tab1, tab2, tab3 = st.tabs(
    [
        "🌡️ Temperature",
        "🌿 Green Cover",
        "🌍 CO₂"
    ]
)


with tab1:

    fig, ax = plt.subplots(figsize=(8,4))

    ax.bar(
        ["Baseline", "Scenario"],
        [
            result["temperature_before"],
            result["temperature_after"]
        ]
    )

    ax.set_ylabel("Temperature (°C)")
    ax.set_title("Estimated Temperature Change")
    ax.grid(axis="y", alpha=0.2)

    st.pyplot(fig)

    plt.close(fig)


with tab2:

    fig, ax = plt.subplots(figsize=(8,4))

    ax.bar(
        ["Baseline", "Scenario"],
        [
            result["green_before"],
            result["green_after"]
        ]
    )

    ax.set_ylabel("Green Cover (%)")
    ax.set_title("Estimated Green Cover Change")
    ax.grid(axis="y", alpha=0.2)

    st.pyplot(fig)

    plt.close(fig)


with tab3:

    fig, ax = plt.subplots(figsize=(8,4))

    ax.bar(
        ["Low Estimate", "High Estimate"],
        [
            result["co2_low"],
            result["co2_high"]
        ]
    )

    ax.set_ylabel(
        "CO₂ Removal (tons/year)"
    )

    ax.set_title(
        "Estimated Annual CO₂ Removal"
    )

    ax.grid(
        axis="y",
        alpha=0.2
    )

    st.pyplot(fig)

    plt.close(fig)


# =========================================================
# SCENARIO COMPARISON
# =========================================================

st.markdown(
    '<div class="section-title">🌳 Planting Scenarios</div>',
    unsafe_allow_html=True
)

scenario_trees = [
    100_000,
    250_000,
    500_000,
    1_000_000
]

scenario_results = []


for number in scenario_trees:

    x = run_ecosim(
        number,
        area
    )

    scenario_results.append({

        "Trees Planted":
            number,

        "Surviving Trees":
            x["surviving_trees"],

        "Canopy (km²)":
            round(
                x["added_canopy"],
                2
            ),

        "Cooling (°C)":
            round(
                x["cooling"],
                2
            ),

        "Temperature (°C)":
            round(
                x["temperature_after"],
                2
            ),

        "CO₂ Low":
            round(
                x["co2_low"]
            ),

        "CO₂ High":
            round(
                x["co2_high"]
            )
    })


scenario_df = pd.DataFrame(
    scenario_results
)


st.dataframe(
    scenario_df,
    use_container_width=True,
    hide_index=True
)


# =========================================================
# SCENARIO GRAPH
# =========================================================

fig, ax = plt.subplots(figsize=(9,4))

ax.plot(
    scenario_df["Trees Planted"],
    scenario_df["Cooling (°C)"],
    marker="o"
)

ax.set_xlabel("Trees Planted")
ax.set_ylabel("Estimated Cooling (°C)")

ax.set_title(
    "Trees vs Estimated Cooling"
)

ax.grid(alpha=0.2)

st.pyplot(fig)

plt.close(fig)


# =========================================================
# SATELLITE MAP
# =========================================================

st.markdown(
    '<div class="section-title">🛰️ Karachi Intervention Map</div>',
    unsafe_allow_html=True
)

st.write(
    "Switch between the standard map and satellite imagery using the layer control."
)


karachi_map = folium.Map(

    location=[
        24.86,
        67.01
    ],

    zoom_start=10,

    tiles="OpenStreetMap"
)


# Satellite layer

folium.TileLayer(

    tiles=
    "https://server.arcgisonline.com/"
    "ArcGIS/rest/services/"
    "World_Imagery/MapServer/tile/"
    "{z}/{y}/{x}",

    attr="Esri World Imagery",

    name="🛰️ Satellite Imagery",

    overlay=False,

    control=True

).add_to(
    karachi_map
)


# Intervention zone

radius = max(
    1500,
    min(
        12000,
        (area ** 0.5) * 1000
    )
)


folium.Circle(

    location=[
        24.86,
        67.01
    ],

    radius=radius,

    popup=
    f"EcoSim AI intervention zone: {area} km²",

    tooltip=
    "EcoSim AI Intervention Zone",

    fill=True,

    fill_opacity=0.18

).add_to(
    karachi_map
)


folium.Marker(

    [
        24.86,
        67.01
    ],

    popup=
    "🌍 EcoSim AI — Karachi",

    tooltip=
    "Karachi"

).add_to(
    karachi_map
)


folium.LayerControl().add_to(
    karachi_map
)


st_folium(
    karachi_map,
    width=None,
    height=520
)


# =========================================================
# QR CODE
# =========================================================

st.markdown(
    '<div class="section-title">📱 Try EcoSim AI</div>',
    unsafe_allow_html=True
)

QR_URL = (
    "https://ecosim-ai-kev2rqhghzx5aznjle885q.streamlit.app/"
)

qr = qrcode.QRCode(
    version=1,
    box_size=10,
    border=4
)

qr.add_data(QR_URL)
qr.make(fit=True)

qr_image = qr.make_image(
    fill_color="#075c38",
    back_color="white"
)

buffer = BytesIO()
qr_image.save(buffer, format="PNG")
buffer.seek(0)


qr_col1, qr_col2 = st.columns([1, 2])


with qr_col1:

    st.image(
        buffer,
        width=230
    )


with qr_col2:

    st.markdown("""
    <div class="card">

    <h3>🌍 Explore the Live Simulation</h3>

    <p>
    Scan the QR code to open the EcoSim AI
    climate simulation on your phone.
    </p>

    <p>
    Judges can change the number of trees,
    intervention area and observe the estimated
    environmental impact.
    </p>

    </div>
    """, unsafe_allow_html=True)


# =========================================================
# KARACHI BASELINE
# =========================================================

st.markdown(
    '<div class="section-title">🏙️ Karachi Baseline Data</div>',
    unsafe_allow_html=True
)


baseline_df = pd.DataFrame({

    "Indicator": [

        "City Area",
        "Buildings",
        "Parks",
        "Park Area",
        "Water Bodies",
        "Water Area",
        "Current Green Cover"

    ],

    "Value": [

        f"{KARACHI_AREA:,.2f} km²",
        f"{BUILDINGS:,}",
        f"{PARKS:,}",
        f"{PARK_AREA:.2f} km²",
        f"{WATER_BODIES:,}",
        f"{WATER_AREA:.2f} km²",
        f"{BASE_GREEN:.3f}%"

    ]

})


st.dataframe(
    baseline_df,
    use_container_width=True,
    hide_index=True
)


# =========================================================
# FOOTER
# =========================================================

st.markdown("""
<div class="footer">

🌍 <b>EcoSim AI</b>
<br>
Karachi Climate Simulation Lab
<br><br>

SDG 11 • Sustainable Cities & Communities
&nbsp; | &nbsp;
SDG 13 • Climate Action

</div>
""", unsafe_allow_html=True)
